import type { Category } from '../model/product'

export interface ProductPhoto {
  n: number
  slug: string
  category: Category
  suggestedCount: number
}

// Порядок совпадает с docs/product-photos.md (категория → имя).
// Файл генерируется скриптом scripts/generate-product-photos.ts.
export const PRODUCT_PHOTOS: ProductPhoto[] = [
  { n: 1, slug: 'amd-ryzen-5-5600', category: 'cpu', suggestedCount: 1 },
  { n: 2, slug: 'amd-ryzen-5-7500f', category: 'cpu', suggestedCount: 1 },
  { n: 3, slug: 'amd-ryzen-5-7600', category: 'cpu', suggestedCount: 1 },
  { n: 4, slug: 'amd-ryzen-5-8600g', category: 'cpu', suggestedCount: 1 },
  { n: 5, slug: 'amd-ryzen-5-9600x', category: 'cpu', suggestedCount: 1 },
  { n: 6, slug: 'amd-ryzen-7-5700x', category: 'cpu', suggestedCount: 1 },
  { n: 7, slug: 'amd-ryzen-7-7800x3d', category: 'cpu', suggestedCount: 1 },
  { n: 8, slug: 'amd-ryzen-7-8700g', category: 'cpu', suggestedCount: 1 },
  { n: 9, slug: 'amd-ryzen-7-9700x', category: 'cpu', suggestedCount: 1 },
  { n: 10, slug: 'amd-ryzen-7-9800x3d', category: 'cpu', suggestedCount: 2 },
  { n: 11, slug: 'amd-ryzen-9-7950x', category: 'cpu', suggestedCount: 1 },
  { n: 12, slug: 'amd-ryzen-9-9900x', category: 'cpu', suggestedCount: 1 },
  { n: 13, slug: 'amd-ryzen-9-9950x', category: 'cpu', suggestedCount: 2 },
  { n: 14, slug: 'intel-core-i5-12400f', category: 'cpu', suggestedCount: 1 },
  { n: 15, slug: 'intel-core-i5-14600kf', category: 'cpu', suggestedCount: 1 },
  { n: 16, slug: 'intel-core-i7-14700k', category: 'cpu', suggestedCount: 1 },
  { n: 17, slug: 'intel-core-i7-14700kf', category: 'cpu', suggestedCount: 1 },
  { n: 18, slug: 'intel-core-i9-14900k', category: 'cpu', suggestedCount: 1 },
  { n: 19, slug: 'intel-core-ultra-9-285k', category: 'cpu', suggestedCount: 2 },
  { n: 20, slug: 'asrock-phantom-gaming-radeon-rx-9070-16', category: 'gpu', suggestedCount: 2 },
  { n: 21, slug: 'asrock-radeon-rx-7800-xt-challenger-16', category: 'gpu', suggestedCount: 2 },
  { n: 22, slug: 'asus-rog-strix-geforce-rtx-5080-oc-16', category: 'gpu', suggestedCount: 3 },
  { n: 23, slug: 'asus-tuf-gaming-geforce-rtx-4070-super-12', category: 'gpu', suggestedCount: 2 },
  { n: 24, slug: 'asus-tuf-gaming-geforce-rtx-5070-ti-oc-16', category: 'gpu', suggestedCount: 3 },
  {
    n: 25,
    slug: 'gigabyte-geforce-rtx-4070-super-windforce-oc-12',
    category: 'gpu',
    suggestedCount: 2,
  },
  {
    n: 26,
    slug: 'gigabyte-geforce-rtx-4080-super-windforce-3x-16',
    category: 'gpu',
    suggestedCount: 2,
  },
  { n: 27, slug: 'gigabyte-geforce-rtx-5070-windforce-oc-12', category: 'gpu', suggestedCount: 2 },
  { n: 28, slug: 'intel-arc-b570-limited-edition-10', category: 'gpu', suggestedCount: 2 },
  { n: 29, slug: 'intel-arc-b580-limited-edition-12', category: 'gpu', suggestedCount: 2 },
  { n: 30, slug: 'msi-geforce-rtx-4060-ventus-2x-8', category: 'gpu', suggestedCount: 2 },
  { n: 31, slug: 'msi-geforce-rtx-4070-ti-super-ventus-3x-16', category: 'gpu', suggestedCount: 2 },
  { n: 32, slug: 'msi-geforce-rtx-5060-ti-ventus-16', category: 'gpu', suggestedCount: 2 },
  { n: 33, slug: 'msi-geforce-rtx-5070-gaming-trio-oc-12', category: 'gpu', suggestedCount: 2 },
  { n: 34, slug: 'palit-geforce-rtx-4060-dual-8', category: 'gpu', suggestedCount: 2 },
  { n: 35, slug: 'palit-geforce-rtx-4060-ti-dual-16', category: 'gpu', suggestedCount: 2 },
  { n: 36, slug: 'palit-geforce-rtx-4070-super-dual-12', category: 'gpu', suggestedCount: 2 },
  {
    n: 37,
    slug: 'palit-geforce-rtx-4070-ti-super-gamingpro-16',
    category: 'gpu',
    suggestedCount: 2,
  },
  { n: 38, slug: 'palit-geforce-rtx-5060-dual-8', category: 'gpu', suggestedCount: 2 },
  { n: 39, slug: 'palit-geforce-rtx-5070-dual-12', category: 'gpu', suggestedCount: 2 },
  { n: 40, slug: 'palit-geforce-rtx-5080-gamingpro-16', category: 'gpu', suggestedCount: 3 },
  { n: 41, slug: 'palit-geforce-rtx-5090-gamingpro-32', category: 'gpu', suggestedCount: 3 },
  { n: 42, slug: 'powercolor-hellhound-radeon-rx-7900-xtx-24', category: 'gpu', suggestedCount: 3 },
  { n: 43, slug: 'sapphire-nitro-radeon-rx-9070-xt-16', category: 'gpu', suggestedCount: 3 },
  { n: 44, slug: 'sapphire-pulse-radeon-rx-7600-8', category: 'gpu', suggestedCount: 2 },
  { n: 45, slug: 'sapphire-pulse-radeon-rx-7600-xt-16', category: 'gpu', suggestedCount: 2 },
  { n: 46, slug: 'sapphire-pulse-radeon-rx-7800-xt-16', category: 'gpu', suggestedCount: 2 },
  { n: 47, slug: 'sapphire-pulse-radeon-rx-7900-xt-20', category: 'gpu', suggestedCount: 2 },
  { n: 48, slug: 'adata-xpg-lancer-blade-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 1 },
  {
    n: 49,
    slug: 'corsair-dominator-titanium-ddr5-32-2x16-7200',
    category: 'ram',
    suggestedCount: 1,
  },
  { n: 50, slug: 'corsair-vengeance-ddr5-16-2x8-5600', category: 'ram', suggestedCount: 1 },
  { n: 51, slug: 'corsair-vengeance-ddr5-16-2x8-6000', category: 'ram', suggestedCount: 1 },
  { n: 52, slug: 'corsair-vengeance-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 1 },
  { n: 53, slug: 'corsair-vengeance-ddr5-64-2x32-6000', category: 'ram', suggestedCount: 1 },
  { n: 54, slug: 'corsair-vengeance-lpx-ddr4-32-2x16-3200', category: 'ram', suggestedCount: 1 },
  { n: 55, slug: 'crucial-pro-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 1 },
  {
    n: 56,
    slug: 'g-skill-trident-z5-neo-rgb-ddr5-32-2x16-6000',
    category: 'ram',
    suggestedCount: 2,
  },
  { n: 57, slug: 'g-skill-trident-z5-rgb-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 2 },
  { n: 58, slug: 'kingston-fury-beast-ddr4-16-2x8-3200', category: 'ram', suggestedCount: 1 },
  { n: 59, slug: 'kingston-fury-beast-ddr4-32-2x16-3200', category: 'ram', suggestedCount: 1 },
  { n: 60, slug: 'kingston-fury-beast-ddr5-16-2x8-6000', category: 'ram', suggestedCount: 1 },
  { n: 61, slug: 'kingston-fury-beast-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 1 },
  { n: 62, slug: 'kingston-fury-beast-ddr5-64-2x32-5600', category: 'ram', suggestedCount: 1 },
  { n: 63, slug: 'kingston-fury-renegade-ddr4-32-2x16-3600', category: 'ram', suggestedCount: 1 },
  { n: 64, slug: 'kingston-fury-renegade-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 1 },
  { n: 65, slug: 'kingston-fury-renegade-ddr5-32-2x16-6400', category: 'ram', suggestedCount: 1 },
  { n: 66, slug: 'kingston-fury-renegade-ddr5-64-2x32-6000', category: 'ram', suggestedCount: 1 },
  { n: 67, slug: 'patriot-viper-venom-ddr5-32-2x16-6000', category: 'ram', suggestedCount: 1 },
  {
    n: 68,
    slug: 'team-group-t-force-delta-rgb-ddr5-32-2x16-6000',
    category: 'ram',
    suggestedCount: 2,
  },
  { n: 69, slug: 'adata-xpg-sx8200-pro-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 70, slug: 'crucial-bx500-1-sata-2-5', category: 'storage', suggestedCount: 1 },
  { n: 71, slug: 'crucial-bx500-2-sata-2-5', category: 'storage', suggestedCount: 1 },
  { n: 72, slug: 'crucial-p310-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 73, slug: 'crucial-t500-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 74, slug: 'crucial-t500-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 75, slug: 'kingston-fury-renegade-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 76, slug: 'kingston-fury-renegade-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 77, slug: 'kingston-nv2-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 78, slug: 'kingston-nv2-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 79, slug: 'kingston-nv2-500-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 80, slug: 'kingston-nv3-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 81, slug: 'kingston-nv3-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 82, slug: 'kingston-nv3-500-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 83, slug: 'lexar-nm790-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 84, slug: 'lexar-nm790-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 85, slug: 'patriot-p300-512-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 86, slug: 'samsung-870-evo-1-sata-2-5', category: 'storage', suggestedCount: 1 },
  { n: 87, slug: 'samsung-870-evo-500-sata-2-5', category: 'storage', suggestedCount: 1 },
  { n: 88, slug: 'samsung-980-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 89, slug: 'samsung-990-pro-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 90, slug: 'samsung-990-pro-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 91, slug: 'samsung-990-pro-4-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 92, slug: 'sandisk-ultra-3d-1-sata-2-5', category: 'storage', suggestedCount: 1 },
  { n: 93, slug: 'silicon-power-ud90-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 94, slug: 'wd-black-sn850x-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 95, slug: 'wd-black-sn850x-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 96, slug: 'wd-black-sn850x-4-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 97, slug: 'wd-blue-sa510-1-sata-2-5', category: 'storage', suggestedCount: 1 },
  { n: 98, slug: 'wd-blue-sn580-1-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 99, slug: 'wd-blue-sn580-2-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 100, slug: 'wd-blue-sn580-500-nvme-m-2', category: 'storage', suggestedCount: 1 },
  { n: 101, slug: 'asrock-b650e-pg-riptide-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 102, slug: 'asrock-b650m-pro-rs', category: 'motherboard', suggestedCount: 1 },
  { n: 103, slug: 'asus-prime-b760-plus-ddr4', category: 'motherboard', suggestedCount: 1 },
  {
    n: 104,
    slug: 'asus-rog-strix-b650e-f-gaming-wifi',
    category: 'motherboard',
    suggestedCount: 1,
  },
  {
    n: 105,
    slug: 'asus-rog-strix-b760-a-gaming-wifi-ddr5',
    category: 'motherboard',
    suggestedCount: 1,
  },
  { n: 106, slug: 'asus-tuf-gaming-b650-plus-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 107, slug: 'asus-tuf-gaming-x870-plus-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 108, slug: 'gigabyte-b650-aorus-elite-ax', category: 'motherboard', suggestedCount: 1 },
  { n: 109, slug: 'gigabyte-b650m-aorus-elite-ax', category: 'motherboard', suggestedCount: 1 },
  { n: 110, slug: 'gigabyte-b760-gaming-x-ddr4', category: 'motherboard', suggestedCount: 1 },
  { n: 111, slug: 'gigabyte-z790-aorus-elite-ax-ddr5', category: 'motherboard', suggestedCount: 1 },
  { n: 112, slug: 'msi-b650m-gaming-plus-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 113, slug: 'msi-mag-b650-tomahawk-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 114, slug: 'msi-mag-b760-tomahawk-wifi-ddr5', category: 'motherboard', suggestedCount: 1 },
  { n: 115, slug: 'msi-mag-z790-tomahawk-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 116, slug: 'msi-mpg-x670e-carbon-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 117, slug: 'msi-x870-tomahawk-wifi', category: 'motherboard', suggestedCount: 1 },
  { n: 118, slug: 'be-quiet-pure-power-12-m-650w', category: 'psu', suggestedCount: 1 },
  { n: 119, slug: 'be-quiet-pure-power-12-m-850w', category: 'psu', suggestedCount: 1 },
  { n: 120, slug: 'be-quiet-straight-power-12-1000w', category: 'psu', suggestedCount: 1 },
  { n: 121, slug: 'chieftec-polaris-750w-gold', category: 'psu', suggestedCount: 1 },
  { n: 122, slug: 'cooler-master-mwe-gold-750-v2', category: 'psu', suggestedCount: 1 },
  { n: 123, slug: 'corsair-rm1000x-atx-3-1', category: 'psu', suggestedCount: 1 },
  { n: 124, slug: 'corsair-rm1200x-shift-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 125, slug: 'corsair-rm750e-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 126, slug: 'corsair-rm850e-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 127, slug: 'cougar-gex-850-gold', category: 'psu', suggestedCount: 1 },
  { n: 128, slug: 'deepcool-pn1000m-gold', category: 'psu', suggestedCount: 1 },
  { n: 129, slug: 'deepcool-pn850m-gold', category: 'psu', suggestedCount: 1 },
  { n: 130, slug: 'msi-mag-a850gl-pcie5', category: 'psu', suggestedCount: 1 },
  { n: 131, slug: 'nzxt-c850-gold-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 132, slug: 'seasonic-focus-gx-750-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 133, slug: 'seasonic-focus-gx-850-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 134, slug: 'seasonic-vertex-gx-1000-atx-3-0', category: 'psu', suggestedCount: 1 },
  { n: 135, slug: 'arctic-liquid-freezer-iii-240', category: 'cooling', suggestedCount: 1 },
  { n: 136, slug: 'arctic-liquid-freezer-iii-280', category: 'cooling', suggestedCount: 1 },
  { n: 137, slug: 'arctic-liquid-freezer-iii-360', category: 'cooling', suggestedCount: 1 },
  { n: 138, slug: 'arctic-p12-pwm-pst-120', category: 'cooling', suggestedCount: 1 },
  { n: 139, slug: 'be-quiet-dark-rock-pro-5', category: 'cooling', suggestedCount: 1 },
  { n: 140, slug: 'be-quiet-pure-rock-2', category: 'cooling', suggestedCount: 1 },
  { n: 141, slug: 'deepcool-ak400', category: 'cooling', suggestedCount: 1 },
  { n: 142, slug: 'deepcool-ak400-digital', category: 'cooling', suggestedCount: 1 },
  { n: 143, slug: 'deepcool-ak620', category: 'cooling', suggestedCount: 1 },
  { n: 144, slug: 'deepcool-ls520-se', category: 'cooling', suggestedCount: 1 },
  { n: 145, slug: 'deepcool-ls720', category: 'cooling', suggestedCount: 2 },
  { n: 146, slug: 'deepcool-ls720-se-wh', category: 'cooling', suggestedCount: 2 },
  { n: 147, slug: 'lian-li-galahad-ii-trinity-360', category: 'cooling', suggestedCount: 2 },
  { n: 148, slug: 'msi-mag-coreliquid-i360', category: 'cooling', suggestedCount: 2 },
  { n: 149, slug: 'msi-mag-coreliquid-m360', category: 'cooling', suggestedCount: 2 },
  { n: 150, slug: 'nzxt-kraken-240-rgb', category: 'cooling', suggestedCount: 2 },
  { n: 151, slug: 'thermalright-peerless-assassin-120-se', category: 'cooling', suggestedCount: 1 },
  { n: 152, slug: 'thermalright-phantom-spirit-120-se', category: 'cooling', suggestedCount: 1 },
  { n: 153, slug: 'be-quiet-pure-base-500-fx', category: 'case', suggestedCount: 1 },
  { n: 154, slug: 'be-quiet-pure-base-500dx', category: 'case', suggestedCount: 1 },
  { n: 155, slug: 'corsair-4000d-airflow', category: 'case', suggestedCount: 1 },
  { n: 156, slug: 'corsair-4000d-airflow-white', category: 'case', suggestedCount: 1 },
  { n: 157, slug: 'corsair-5000d-airflow', category: 'case', suggestedCount: 2 },
  { n: 158, slug: 'deepcool-ch510-mesh-digital', category: 'case', suggestedCount: 1 },
  { n: 159, slug: 'deepcool-ch560-digital', category: 'case', suggestedCount: 1 },
  { n: 160, slug: 'fractal-design-north-charcoal-black', category: 'case', suggestedCount: 2 },
  { n: 161, slug: 'fractal-design-pop-air', category: 'case', suggestedCount: 1 },
  { n: 162, slug: 'jonsbo-d31-mesh', category: 'case', suggestedCount: 1 },
  { n: 163, slug: 'lian-li-lancool-216', category: 'case', suggestedCount: 1 },
  { n: 164, slug: 'lian-li-lancool-216-white', category: 'case', suggestedCount: 1 },
  { n: 165, slug: 'lian-li-o11-vision', category: 'case', suggestedCount: 2 },
  { n: 166, slug: 'montech-air-903-max', category: 'case', suggestedCount: 2 },
  { n: 167, slug: 'nzxt-h5-flow', category: 'case', suggestedCount: 1 },
  { n: 168, slug: 'nzxt-h6-flow', category: 'case', suggestedCount: 2 },
  { n: 169, slug: 'asus-rog-keris-ii-ace', category: 'peripherals', suggestedCount: 1 },
  { n: 170, slug: 'asus-rog-swift-pg27aqn-27-qhd-360', category: 'peripherals', suggestedCount: 2 },
  {
    n: 171,
    slug: 'asus-tuf-gaming-vg27aq3a-27-qhd-180',
    category: 'peripherals',
    suggestedCount: 1,
  },
  { n: 172, slug: 'ducky-one-3-tkl', category: 'peripherals', suggestedCount: 1 },
  { n: 173, slug: 'gigabyte-m27q-27-qhd-170', category: 'peripherals', suggestedCount: 1 },
  { n: 174, slug: 'hyperx-alloy-origins-core', category: 'peripherals', suggestedCount: 1 },
  { n: 175, slug: 'hyperx-cloud-ii', category: 'peripherals', suggestedCount: 1 },
  { n: 176, slug: 'hyperx-cloud-iii', category: 'peripherals', suggestedCount: 1 },
  { n: 177, slug: 'keychron-k8-pro', category: 'peripherals', suggestedCount: 1 },
  { n: 178, slug: 'keychron-q3-qmk', category: 'peripherals', suggestedCount: 1 },
  { n: 179, slug: 'keychron-v3-qmk', category: 'peripherals', suggestedCount: 1 },
  { n: 180, slug: 'lg-ultragear-27gs95qe-27-4k-240', category: 'peripherals', suggestedCount: 2 },
  { n: 181, slug: 'logitech-g-pro-x-superlight-2', category: 'peripherals', suggestedCount: 2 },
  { n: 182, slug: 'logitech-g-pro-x-tkl', category: 'peripherals', suggestedCount: 1 },
  { n: 183, slug: 'logitech-g305-lightspeed', category: 'peripherals', suggestedCount: 1 },
  { n: 184, slug: 'logitech-g413-tkl-se', category: 'peripherals', suggestedCount: 1 },
  { n: 185, slug: 'logitech-g435-lightspeed', category: 'peripherals', suggestedCount: 1 },
  { n: 186, slug: 'logitech-g502-x', category: 'peripherals', suggestedCount: 1 },
  { n: 187, slug: 'logitech-g502-x-plus', category: 'peripherals', suggestedCount: 1 },
  { n: 188, slug: 'msi-g274qpf-27-qhd-170', category: 'peripherals', suggestedCount: 1 },
  { n: 189, slug: 'razer-deathadder-v3', category: 'peripherals', suggestedCount: 1 },
  { n: 190, slug: 'razer-viper-v3-pro', category: 'peripherals', suggestedCount: 2 },
  { n: 191, slug: 'samsung-odyssey-g5-27-qhd-144', category: 'peripherals', suggestedCount: 1 },
  { n: 192, slug: 'steelseries-arctis-nova-5', category: 'peripherals', suggestedCount: 2 },
  { n: 193, slug: 'steelseries-arctis-nova-7', category: 'peripherals', suggestedCount: 2 },
]

const photoBySlug = new Map<string, ProductPhoto>()
const photoByNumber = new Map<number, ProductPhoto>()
for (const photo of PRODUCT_PHOTOS) {
  photoBySlug.set(photo.slug, photo)
  photoByNumber.set(photo.n, photo)
}

export function getProductPhoto(slug: string): ProductPhoto | null {
  return photoBySlug.get(slug) ?? null
}

export function getProductPhotoByNumber(n: number): ProductPhoto | null {
  return photoByNumber.get(n) ?? null
}
